---

sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install 'ansible<2.5'
  - pip install molecule
  - pip install docker-py
script:
  # missing-package molecule disabled
  # - ./bootstrap.sh
  # - .tools/click/bin/python tasks.py molecule
  - molecule test
