---

- name: MailHog folder
  file:
    path: "{{ _mailhog_install_base_folder }}"
    state: directory
    owner: "{{ _powo_misc_user }}"
    group: "{{ _powo_misc_user }}"

- name: MailHog icon
  get_url:
    url: "{{ _mailhog_icon_download_url }}"
    dest: "{{ _mailhog_install_base_folder }}"
    owner: "{{ _powo_misc_user }}"
    group: "{{ _powo_misc_user }}"

- name: Download MailHog_linux_amd64
  get_url:
    url: "{{ _mailhog_download_url }}"
    dest: "{{ _mailhog_install_base_folder }}"
    checksum: "{{ _mailhog_checksum }}"
    owner: "{{ _powo_misc_user }}"
    group: "{{ _powo_misc_user }}"

- name: MailHog check
  check_mode: true
  file:
    state: directory
    path: "{{ _mailhog_install_base_folder }}"
  register: mailhog_check

- name: MailHog_linux_amd64 executable
  file:
    path: "{{ _mailhog_bin_path }}"
    mode: +x

- name: MailHog_linux_amd64 copying file
  copy:
    src: "{{ _mailhog_bin_path }}"
    dest: "{{ _mailhog_install_path }}"

- name: mailhog executable
  file:
    path: "{{ _mailhog_install_path }}"
    mode: +x

- name: update /etc/systemd/system/mailhog.service
  template:
    src: mailhog.service.j2
    dest: /etc/systemd/system/mailhog.service
  register: mailhog_conf_check

- name: start enabled true mailhog
  service:
    name: mailhog
    state: restarted
    enabled: true
  when: mailhog_check.changed or mailhog_conf_check.changed
