---

- name: privileged
  become: true
  become_user: root
  block:
    - name: repository
      include_tasks: "repository_{{ ansible_facts['os_family'] }}.yml"

    - name: google chrome installation
      package: name=google-chrome-stable state=present

    # L9462 - conflit libswresample-free pour passer gnome-shell
    # - name: chromium installation
    #   package: name={{ item }} state=present
    #   with_items: "{{ lookup('distro', chromium_packages) }}"
