---

# mandatory
pu_create: false
pu_user: "{{ lookup('env', 'USER') }}"
pu_group: "{{ pu_user }}"
pu_password: "{{ you must define pu_password }}"
pu_uid: "{{ you must define pu_uid }}"
pu_gid: "{{ pu_uid }}"
pu_shell: "/bin/bash"
pu_groups: []
pu_sudo: false
pu_fullname: "John Doe"
# optional if sshkey already exists
pu_passphrase: "{{ you must define pu_passphrase to create a ssh key}}"

pu_profiles: []
# - filename: my_vars.conf
#   template: |
#     export MY_VAR=toto
# - filename: other_vars.conf
#   template: ...

pu_admin_group: "{{ lookup('distro', pu_admin_group_distro) }}"

pu_admin_group_distro:
  RedHat: wheel
  Debian: admin
